DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
		userId INT UNSIGNED AUTO_INCREMENT NOT NULL,
		handleId VARCHAR(32) NOT NULL,
		UNIQUE(handleId),
		PRIMARY KEY(userId)
);

CREATE TABLE post (
		postId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	   userHandle VARCHAR(32) NOT NULL,
		content VARCHAR (140) NOT NULL,
		FOREIGN KEY (userHandle) REFERENCES ruser(userHandle),
		PRIMARY KEY (postId)
);

CREATE TABLE comments (
		subPost INT UNSIGNED AUTO_INCREMENT NOT NULL,
	   userHandle VARCHAR(32) NOT NULL,
		content VARCHAR (140) NOT NULL,
		FOREIGN KEY (userHandle) REFERENCES ruser (userHandle),
		PRIMARY KEY (subPost)
);



