DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
	userId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	handle VARCHAR(32) NOT NULL,
	UNIQUE(handle),
	PRIMARY KEY(userId)
);

CREATE TABLE post (
	postId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	handle VARCHAR(32) NOT NULL,
	contents VARCHAR (140) NOT NULL,
	FOREIGN KEY (handle) REFERENCES user(handle),
	PRIMARY KEY (postId)
);

CREATE TABLE comment (
	commentId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	postId INT UNSIGNED NOT NULL,
	handle VARCHAR(32) NOT NULL,
	contents VARCHAR (140) NOT NULL,
	FOREIGN KEY (handle) REFERENCES user(handle),
	FOREIGN KEY (postId) REFERENCES post(postId),
	PRIMARY KEY (commentId)
);